### PR TITLE
Pass sbroker-specific options in Args to comply with gen:start's spec

### PR DESCRIPTION
**Pull request by alco**

### CODE REVIEW

**Comment by fishcakez** [comment]
Thanks @alco, this looks like the right fix. Just one nitpick, could we pass the arg term as a 2-tuple? It is very strange to use a cons in that way. That argument to gen:start can be any term.

**Comment by alco** [comment]
@fishcakez I have updated the commit.

**Comment by fishcakez** [comment]
Thanks @alco. Would you like me to push a new hex release? If so I'll do it when I get home in couple hours.

**Comment by alco** [comment]
@fishcakez I'll leave that up to you. We're comfortable using it as a Git dependency until a new release is available.

**Comment by fishcakez** [comment]
I will because I will release a 0.8 next week with some new features. People may nor want to upgrade as I had to break the API to make configuration easier - always configure in milli seconds but measure in native time and the queue controls the timeout so no polling. I know the interval polling was a problem for your folks at one stage.

**Pull request merged**
